# WES : mosdepth fore PRE_BAM

In [4]:
import pandas as pd
import numpy as np
import os
import glob

hg = "hg38"
BAM_DIR = f"/data/project/Meningioma/02.Align/{hg}"

df_acc = pd.DataFrame(columns=["length", "bases", "mean", "min", "max", "DATE", "TISSUE"])

for TISSUE in ["Blood", "Tumor", "Dura", "Ventricle", "Cortex"]:
    file_list = [file for file in glob.glob(f"{BAM_DIR}/{TISSUE}/07.mosdepth/*.mosdepth.summary.txt") if "WGS" not in file]

    for file in file_list:
        DATE = os.path.basename(file).split(f"_{TISSUE}")[0]

        df_individual = pd.read_csv(file, sep="\t")

        # 마지막 row의 1열부터 가져오고 DATE, TISSUE 추가
        t = df_individual.iloc[-1][1:]
        t["DATE"] = DATE
        t["TISSUE"] = TISSUE

        df_acc = pd.concat([df_acc, pd.DataFrame([t])], ignore_index=True)
                
df_acc.sort_values(by=["TISSUE", "DATE"], ascending=True, inplace=True)  # 오름차순으로 정렬
df_acc.reset_index(drop=True, inplace=True)  # 인덱스 초기화

df_acc.to_csv ( "/data/project/Meningioma/script/02.Align&DOC/mosdepth.result.csv", index = False, sep = "\t")
pd.set_option('display.max_rows', 500)
df_acc

       length        bases    mean min    max          DATE TISSUE
0    50446305   6261721067  124.13   0   2093        190426  Blood
1    50446305   6816639706  135.13   0   2173        190524  Blood
2    50446305   7296865098  144.65   0   5362      220930_2  Blood
3    50446305   6084734471  120.62   0   4445        221026  Blood
4    50446305   6441855244  127.70   0    852        221102  Blood
5    50446305   5639973375  111.80   0   1779        221202  Blood
6    50446305   8601369677  170.51   0   4855        230127  Blood
7    50446305   4292154282   85.08   0   1313      230303_1  Blood
8    50446305   8207039116  162.69   0   3420     230323_11  Blood
9    50446305   8206997469  162.69   0   3436      230323_2  Blood
10   50446305   6060794371  120.14   0    767      230405_2  Blood
11   50446305   7279013653  144.29   0   3796        230419  Blood
12   50446305   5331636502  105.69   0   2220        230526  Blood
13   50446305   5173487276  102.55   0   1988      230802_2  Blood
14   50446305   5961043959  118.17   0   2390        230812  Blood
15   50446305   5371293499  106.48   0   1675        230822  Blood
16   50446305   5666667913  112.33   0   1817        230920  Blood
17   50446305   5478829563  108.61   0   2124        231006  Blood
18   50446305   6942522277  137.62   0   2557        231025  Blood
19   50446305   9053864656  179.48   0   4584        231101  Blood
20   50446305   6770589072  134.21   0   2450        231206  Blood
21   50446305   7189819532  142.52   0   3631        240110  Blood
22   50446305   6797352910  134.74   0   2826        240320  Blood
23   50446305   6802229445  134.84   0   2373        240325  Blood
24   50446305   5006635945   99.25   0   1897      240403_3  Blood
25   50446305   5181237883  102.71   0   2141      240412_2  Blood
26   50446305   5946828977  117.88   0   2561        240612  Blood
27   50446305   5705338323  113.10   0   2094        240911  Blood
28   50446305   6645228664  131.73   0   2225        241023  Blood
29   50446305   6411407473  127.09   0   2228        241127  Blood
30   50446305  21884395065  433.82   0   8959        190426   Dura
31   50446305  18713256992  370.95   0   5899        190524   Dura
32   50446305  15933842923  315.86   0   6188      220930_2   Dura
33   50446305  30254992329  599.75   0  19150        221026   Dura
34   50446305  14641563960  290.24   0   2035        221102   Dura
35   50446305  16769585533  332.42   0   5378        221202   Dura
36   50446305  16086492397  318.88   0   7466        230127   Dura
37   50446305  18428650439  365.31   0   6228      230303_1   Dura
38   50446305  11846146109  234.83   0   5123     230323_11   Dura
39   50446305  10322240341  204.62   0   3113      230323_2   Dura
40   50446305  15713451174  311.49   0   4379      230405_2   Dura
41   50446305  13443519043  266.49   0   8451        230419   Dura
42   50446305  18277664461  362.32   0   7887        230526   Dura
43   50446305  16903022485  335.07   0   5304      230802_2   Dura
44   50446305  10404222386  206.24   0   3223        230822   Dura
45   50446305  18979678334  376.24   0   5978        230920   Dura
46   50446305  17897430901  354.78   0   6882        231006   Dura
47   50446305  18760391563  371.89   0   6571        231025   Dura
48   50446305  17818322229  353.21   0   9104        231101   Dura
49   50446305  19534088156  387.23   0   6786        231206   Dura
50   50446305  15209496668  301.50   0   7170        240110   Dura
51   50446305  18935721326  375.36   0   7777        240320   Dura
52   50446305  18841428345  373.49   0   6069        240325   Dura
53   50446305  17174368081  340.45   0   5988      240403_3   Dura
54   50446305  15940902405  316.00   0   6456      240412_2   Dura
55   50446305  18913376212  374.92   0   5990        241023   Dura
56   50446305   6388800971  126.65   0   2250    190426_FFT  Tumor
57   50446305   6036031905  119.65   0   2189    190426_PCT  Tumor
58   50446305   7326676756  145.24   0   2685    190426_PFT  Tumor
59   50446305   6608730330  131.01   0   2246     190426_PP  Tumor
60   50446305   5721739945  113.42   0   1979     190426_PT  Tumor
61   50446305   4942729573   97.98   0   1562        190524  Tumor
62   50446305   6365425886  126.18   0   3681      220930_2  Tumor
63   50446305   6637410022  131.57   0   3965        221026  Tumor
64   50446305   6202062531  122.94   0   1015        221102  Tumor
65   50446305   5677545710  112.55   0   1810        221202  Tumor
66   50446305   7189298017  142.51   0   3335        230127  Tumor
67   50446305   5053062457  100.17   0   1499      230303_1  Tumor
68   50446305   7571245891  150.09   0   2678     230323_11  Tumor
69   50446305   6590557928  130.65   0   2695      230323_2  Tumor
70   50446305   6617338243  131.18   0    924      230405_2  Tumor
71   50446305   7528266101  149.23   0   3128        230419  Tumor
72   50446305   5800864863  114.99   0   2613        230526  Tumor
73   50446305   4304309606   85.32   0   5269      230802_2  Tumor
74   50446305   5466533044  108.36   0   1546        230812  Tumor
75   50446305   5536004762  109.74   0   1847        230822  Tumor
76   50446305   5817611405  115.32   0   2049        230920  Tumor
77   50446305   5962558324  118.20   0   2451        231006  Tumor
78   50446305   5327569174  105.61   0   2010        231025  Tumor
79   50446305   7130909789  141.36   0   3535        231101  Tumor
80   50446305   6157308623  122.06   0   2180        231206  Tumor
81   50446305   5351661236  106.09   0   2497        240110  Tumor
82   50446305   7042454590  139.60   0   3306        240320  Tumor
83   50446305   5513345301  109.29   0   1656        240325  Tumor
84   50446305   7118334394  141.11   0   3586      240403_3  Tumor
85   50446305   5840109951  115.77   0   3661      240412_2  Tumor
86   50446305   5974931454  118.44   0   2024        240612  Tumor
87   50446305   5968676258  118.32   0   2044        240911  Tumor
88   50446305   6763159835  134.07   0   3079        241023  Tumor
89   50446305   6180006866  122.51   0   2078        241127  Tumor
90   50446305   5024863697   99.61   0   1896     241127_FT  Tumor
91   50446305   6648723520  131.80   0   2815   241127_FTRt  Tumor
92   50446305   4620200459   91.59   0   1877   241127_Para  Tumor
93   50446305   5515119448  109.33   0   2768        250310  Tumor
94   50446305   6577760613  130.39   0   2066        250319  Tumor
95   50446305   6658338477  131.99   0   2252        250407  Tumor
96   50446305   6351610515  125.91   0   2194        250408  Tumor
97   50446305   6229698602  123.49   0   2139        250428  Tumor
98   50446305   6519834369  129.24   0   2790        250509  Tumor
99   50446305   5740134658  113.79   0   4247        250513  Tumor
100  50446305   6356837755  126.01   0   2579        250515  Tumor
101  50446305   6370663170  126.29   0   2346        250520  Tumor
102  50446305   6664267895  132.11   0   2315   250526_Left  Tumor
103  50446305   6555772181  129.96   0   2628  250526_Right  Tumor
104  50446305   6140725653  121.73   0   2310        250527  Tumor
105  50446305   5729237473  113.57   0   2128        250530  Tumor
106  50446305   6650301319  131.83   0   2261        250602  Tumor
107  50446305   6570812867  130.25   0   2494        250605  Tumor
108  50446305   6681590550  132.45   0   2497        250609  Tumor

In [3]:
df_acc.groupby("TISSUE")["mean"].agg(["count", "mean", "std"]).reset_index().round(1)

  TISSUE  count   mean   std
0  Blood     30  127.3  22.2
1   Dura     26  341.3  76.4
2  Tumor     53  122.4  14.1

# WES : Depth of Coverage

In [10]:
import pandas as pd
import numpy as np
import os
import glob

hg="hg38"
BAM_DIR="/data/project/Meningioma/02.Align/" + hg

df = pd.DataFrame (columns = list (pd.read_csv ( "/data/project/Meningioma/02.Align/hg38/Dura/06.DepthOfCoverage/221026_Dura.depth.result.sample_summary" , sep = "," ).columns  ) + ["Target_depth", "Cost" ]  )
df = df.astype (float)
df["DATE"] = ""; df["TISSUE"] = ""
df = df.astype ({ 'sample_id':'str', "DATE": "str", "TISSUE" : "str"   })


for TISSUE in ["Blood", "Tumor", "Dura", "Ventricle", "Cortex"]:
    file_list = [file for file in glob.glob(BAM_DIR + "/" + TISSUE + "/06.DepthOfCoverage/*.depth.result.sample_summary") if "WGS" not in file]

    for file in file_list:
        DATE = os.path.basename(file).split( "_" + TISSUE )[0]

        df_individual = pd.read_csv ( file, sep = "," )

        if TISSUE in ["Dura", "Falx"]:
            target_depth = 900
            cost = 159.5
        elif TISSUE in [ "Tumor", "Ventricle", "Cortex", "Blood"]:
            target_depth = 300
            cost = 55
        


        t = pd.Series ( list(df_individual.iloc[0]) +  [target_depth, cost, DATE, TISSUE]  )
        t.index = df.columns
        
    
        df = pd.concat([df, pd.DataFrame([t])], ignore_index=True)
        


df.rename(columns = {"granular_median":"median" }, inplace = True)
df = df.astype ( {"median" : "int", "Target_depth" : "int"})


df [["sample_id", "DATE", "TISSUE", "Target_depth", "median", "Cost" ]].to_csv ( "/data/project/Meningioma/script/02.Align&DOC/depthofcoverage.result.csv", index = False, sep = "\t")
df [["sample_id", "DATE", "TISSUE", "Target_depth", "median", "mean" ]]

           sample_id       DATE     TISSUE  Target_depth  median    mean
0       230822_Blood     230822      Blood           300     108  106.25
1       241127_Blood     241127      Blood           300     129  128.25
2       221026_Blood     221026      Blood           300     123  141.26
3       221102_Blood     221102      Blood           300     116  112.42
4       230920_Blood     230920      Blood           300     111  109.98
5       240911_Blood     240911      Blood           300     115  113.93
6     240412_3_Blood   240412_3      Blood           300      97   96.38
7       240325_Blood     240325      Blood           300     144  140.28
8       240320_Blood     240320      Blood           300     138  137.02
9       230127_Blood     230127      Blood           300     159  182.83
10      230405_Blood     230405      Blood           300     110  106.03
11      240612_Blood     240612      Blood           300     120  123.19
12    240403_3_Blood   240403_3      Blood           300      92   92.00
13   230323_11_Blood  230323_11      Blood           300     161  183.33
14      190524_Blood     190524      Blood           300     139  137.37
15      230812_Blood     230812      Blood           300     121  121.23
16    230802_3_Blood   230802_3      Blood           300      96   96.07
17      231025_Blood     231025      Blood           300     141  139.75
18      230323_Blood     230323      Blood           300     161  183.33
19      231206_Blood     231206      Blood           300     138  136.51
20      241023_Blood     241023      Blood           300     134  133.01
21      230419_Blood     230419      Blood           300     148  168.68
22      221026_Tumor     221026      Tumor           300     132  155.48
23      240320_Tumor     240320      Tumor           300     142  143.16
24    240403_3_Tumor   240403_3      Tumor           300     156  161.46
25      240325_Tumor     240325      Tumor           300     108  107.22
26      231025_Tumor     231025      Tumor           300     103  104.33
27      230127_Tumor     230127      Tumor           300     144  168.23
28    240412_3_Tumor   240412_3      Tumor           300     119  121.66
29   230323_11_Tumor  230323_11      Tumor           300     147  147.80
30      231206_Tumor     231206      Tumor           300     118  119.74
31      221102_Tumor     221102      Tumor           300     108  109.44
32      230920_Tumor     230920      Tumor           300     115  114.37
33      240911_Tumor     240911      Tumor           300     114  115.45
34      230419_Tumor     230419      Tumor           300     141  167.71
35      230822_Tumor     230822      Tumor           300     113  111.48
36    230802_3_Tumor   230802_3      Tumor           300     166  168.70
37      190524_Tumor     190524      Tumor           300      96   96.65
38      241127_Tumor     241127      Tumor           300     126  126.33
39      241023_Tumor     241023      Tumor           300     131  136.70
40       240325_Dura     240325       Dura           900     383  377.69
41     230405_2_Dura   230405_2       Dura           900     301  299.07
42       190524_Dura     190524       Dura           900     378  373.31
43       230323_Dura     230323       Dura           900     221  252.24
44    230323_11_Dura  230323_11       Dura           900     221  252.24
45       231206_Dura     231206       Dura           900     400  392.89
46       230920_Dura     230920       Dura           900     369  364.01
47     240412_3_Dura   240412_3       Dura           900     296  297.79
48       221026_Dura     221026       Dura           900     305  355.20
49       221102_Dura     221102       Dura           900     264  254.90
50     240403_3_Dura   240403_3       Dura           900     326  327.50
51     230802_3_Dura   230802_3       Dura           900     315  316.82
52       230405_Dura     230405       Dura           900     243  233.43
53     230323_2_Dura   230323_2       Dura           900     200  198.01
54       240320_Dura     240320       Dura           900     384  378.98
55       230419_Dura     230419       Dura           900     239  272.63
56       230127_Dura     230127       Dura           900     296  338.22
57  230419_Ventricle     230419  Ventricle           300     268  305.52
58     230127_Cortex     230127     Cortex           300     218  252.65

In [18]:
df.groupby("TISSUE")["mean"].agg(["mean", "std"]).reset_index().round(1)

      TISSUE   mean   std
0      Blood  131.3  27.9
1     Cortex  252.6   NaN
2       Dura  310.9  59.2
3      Tumor  132.0  24.5
4  Ventricle  305.5   NaN

# AS; Read count 직접 계산

### Multiplex PCR

In [43]:
multiplex_df = pd.read_csv("/data/project/Meningioma/51.Amplicon/08.multiplex_250227/07.pysam/multiplex_count_df.tsv", sep="\t",index_col = 0) 
multiplex_df_acc = pd.DataFrame ( columns = ["position", "read_depth"])
for col_i, col in enumerate ( multiplex_df.columns ):
    for row_i, row in enumerate ( multiplex_df.index ):
        ref_alt = multiplex_df.iloc [ row_i, col_i ]
        alt = int(ref_alt.split("/")[1])
        if alt != 0:
            multiplex_df_acc = pd.concat( [ multiplex_df_acc,  pd.DataFrame([[col, alt]], columns=["position", "read_depth"] ) ], ignore_index=True)


multiplex_df_acc.groupby("position")["read_depth"].agg(["mean", "std"]).reset_index().round(1)
multiplex_df_acc["read_depth"].agg(["mean", "std"]).round(1)

mean    1077216.0
std     1313202.8
Name: read_depth, dtype: float64

In [52]:
single_df_acc = pd.DataFrame ( columns = ["position",  "Sample_ID", "read_depth"])
file_list = [file for file in glob.glob( "/data/project/Meningioma/51.Amplicon/01.single/07.pysam/*count_df.tsv" ) ]

for file in file_list:
    POSITION = os.path.basename(file).split( "_count_df.tsv" )[0]
    print ( POSITION)
    
    single_df = pd.read_csv( file, sep="\t",index_col = 0) 
    for col_i, col in enumerate ( single_df.columns ):
        for row_i, row in enumerate ( single_df.index ):
            ref_alt = single_df.iloc [ row_i, col_i ]
            alt = int(ref_alt.split("/")[1])
            if alt != 0:
                single_df_acc = pd.concat( [ single_df_acc,  pd.DataFrame([[col, row, alt]], columns=["position", "Sample_ID", "read_depth"] ) ], ignore_index=True)
single_df_acc
single_df_acc["read_depth"].agg(["mean", "std"]).round(1)

chr22_29639168
chr22_29655663
chr22_29636758
chr16_2175609
chr14_104780214
chr16_2176145
chr9_107487067
chr22_29673365
chr22_29661335
chr22_29604113
chr16_2175939
chr22_29604050

mean    9886604.3
std     4186845.0
Name: read_depth, dtype: float64

---

### 전체 data의 DOC를 확인해보기

In [5]:
import pandas as pd
import numpy as np
import os

hg="hg38"
DATA_PATH="/data/project/Meningioma/02.Align/" + hg
datenames = sorted ( [line.rstrip('\n') for line in open('/data/project/Meningioma/script/sample_name.txt', 'r')]  )  # ['220930', '220930', '220930']



df = pd.DataFrame (columns = list (pd.read_csv ( "/data/project/Meningioma/02.Align/hg38/Dura/06.DepthOfCoverage/221026_Dura.depth.result.sample_summary" , sep = "," ).columns  ) + ["Target_depth", "Cost", "Corp"]  )
df = df.astype (float)
df = df.astype ({'sample_id':'str' , 'Corp':'str'  })


for tissue in ["Blood", "Tumor", "Dura", "Ventricle", "Cortex"]:
    for date in datenames:
        samplename = "{}_{}".format(date, tissue)
        INPUT_DOC =  DATA_PATH + "/" + tissue + "/06.DepthOfCoverage/" + samplename + ".depth.result.sample_summary"

        if os.path.exists (INPUT_DOC) == True:
            df_individual = pd.read_csv (INPUT_DOC, sep = "," )


            if date in ["220930", "221026", "230127", "230323", "230419"]:
                corp = "Theragen"
                if tissue == "Dura":
                    target_depth = 1000 if date == "221026" else 500
                    cost = 159.5 if date == "221026" else 107.25
                elif tissue in ["Ventricle", "Cortex"]:
                    target_depth = 500
                    cost = 107.25
                elif tissue in ["Blood", "Tumor"]:
                    target_depth = 300
                    cost = 88

            else:
                corp = "Macrogen"
                if tissue == "Dura":
                    target_depth = 500
                    cost = 99
                elif tissue in ["Ventricle", "Cortex"]:
                    target_depth = 500
                    cost = 99
                elif tissue in ["Blood", "Tumor"]:
                    target_depth = 300
                    cost = 49.5
            
            t = pd.Series ( list(df_individual.iloc[0]) +  [target_depth] + [cost] + [corp] )
            t.index = df.columns
            
        
            df = df.append( pd.Series(t) , ignore_index = True)    #개별 sample row만 합쳐준다
            


df.rename(columns = {"granular_median":"median" }, inplace = True)
df = df.astype ( {"median" : "int", "Target_depth" : "int"})


df [["sample_id", "Target_depth", "median", "Cost", "Corp"]].to_csv ( "/data/project/Meningioma/script/02.Align&DOC/depthofcoverage.result.csv", index = False, sep = "\t")
df [["sample_id", "Target_depth", "median", "mean", "Corp"]]

           sample_id  Target_depth  median    mean      Corp
0       220930_Blood           300     147  169.38  Theragen
1       221026_Blood           300     123  141.26  Theragen
2       221102_Blood           300     116  112.42  Macrogen
3       230127_Blood           300     159  182.83  Theragen
4       230323_Blood           300     161  183.33  Theragen
5       230405_Blood           300     110  106.03  Macrogen
6       230419_Blood           300     148  168.68  Theragen
7       220930_Tumor           300     125  150.31  Theragen
8       221026_Tumor           300     132  155.48  Theragen
9       221102_Tumor           300     108  109.44  Macrogen
10      230127_Tumor           300     144  168.23  Theragen
11      230323_Tumor           300     129  148.37  Theragen
12      230405_Tumor           300     116  114.69  Macrogen
13      230419_Tumor           300     141  167.71  Theragen
14       220930_Dura           500     197  228.50  Theragen
15       221026_Dura          1000     305  355.20  Theragen
16       221102_Dura           500     264  254.90  Macrogen
17       230127_Dura           500     296  338.22  Theragen
18       230323_Dura           500     221  252.24  Theragen
19       230405_Dura           500     243  233.43  Macrogen
20       230419_Dura           500     239  272.63  Theragen
21  230419_Ventricle           500     268  305.52  Theragen
22     230127_Cortex           500     218  252.65  Theragen

In [4]:
df

,sample_id,total,mean,granular_third_quartile,median,granular_first_quartile,%_bases_above_15,Target_depth,Cost,Corp
0,220930_Blood,8.539370e+09,169.38,226.0,147,89.0,99.1,300,88.00,Theragen
1,221026_Blood,7.121894e+09,141.26,189.0,123,74.0,98.8,300,88.00,Theragen
2,221102_Blood,5.667659e+09,112.42,144.0,116,83.0,94.9,300,49.50,Macrogen
3,230127_Blood,9.217555e+09,182.83,244.0,159,97.0,99.2,300,88.00,Theragen
4,230323_Blood,9.242876e+09,183.33,245.0,161,99.0,99.1,300,88.00,Theragen
5,230405_Blood,5.345851e+09,106.03,136.0,110,78.0,94.8,300,49.50,Macrogen
6,230419_Blood,8.504073e+09,168.68,225.0,148,90.0,99.0,300,88.00,Theragen
7,220930_Tumor,7.578200e+09,150.31,201.0,125,73.0,98.5,300,88.00,Theragen
8,221026_Tumor,7.838875e+09,155.48,208.0,132,79.0,98.8,300,88.00,Theragen
9,221102_Tumor,5.517502e+09,109.44,141.0,108,75.0,94.9,300,49.50,Macrogen
10,230127_Tumor,8.481691e+09,168.23,225.0,144,86.0,98.9,300,88.00,Theragen
11,230323_Tumor,7.480382e+09,148.37,198.0,129,78.0,98.7,300,88.00,Theragen
12,230405_Tumor,5.782139e+09,114.69,147.0,116,83.0,95.0,300,49.50,Macrogen
13,230419_Tumor,8.455452e+09,167.71,223.0,141,85.0,98.8,300,88.00,Theragen
14,220930_Dura,1.152004e+10,228.50,304.0,197,118.0,99.4,500,107.25,Theragen
15,221026_Dura,1.790796e+10,355.20,471.0,305,187.0,99.7,1000,159.50,Theragen
16,221102_Dura,1.285137e+10,254.90,327.0,264,189.0,95.3,500,99.00,Macrogen
17,230127_Dura,1.705196e+10,338.22,451.0,296,180.0,99.7,500,107.25,Theragen
18,230323_Dura,1.271685e+10,252.24,336.0,221,136.0,99.4,500,107.25,Theragen
19,230405_Dura,1.176860e+10,233.43,300.0,243,172.0,95.2,500,99.00,Macrogen
20,230419_Dura,1.374487e+10,272.63,363.0,239,145.0,99.4,500,107.25,Theragen
21,230419_Ventricle,1.540326e+10,305.52,407.0,268,164.0,99.5,500,107.25,Theragen
22,230127_Cortex,1.273767e+10,252.65,336.0,218,132.0,99.5,500,107.25,Theragen

# 연습장

In [3]:
maf_colnames = ['Chromosome', 'Start_Position', 'End_Position',
                'Tumor_Sample_Barcode', "ID", 'Hugo_Symbol', 'Reference_Allele',
                'Tumor_Seq_Allele2',  "Alt", "Depth", "BIOTYPE", 'Variant_Classification', "Impact",
                'tx', 'exon', "rsID", 'txChange', 'aaChange', 'Variant_Type', 'sample_id',
                'hgnc_symbol', 'Entrez', 'ens_id', 'Entrez_Gene_Id',
                "clinvar_MedGen_id", "clinvar_OMIM_id", "clinvar_Orphanet_id", "clinvar_clnsig", "clinvar_hgvs", "clinvar_id", "clinvar_review", "clinvar_trait", "clinvar_var_source",
                "CLIN_SIG", "SIFT", "PolyPhen",
                "SIFT_pred", "Polyphen2_HDIV_pred", "Polyphen2_HVAR_pred",
                "ClinPred_pred", "ClinPred_rankscore", "ClinPred_score", "DANN_rankscore", "DANN_score",
                "CADD", "GERP++_RS", "FATHMM_pred", "FATHMM_score", 'MetaSVM_pred',  "MetaSVM_rankscore", "MetaSVM_score", "MutationTaster_pred", 'MutationAssessor_pred',
                "SpliceAI_pred_DS_AG", "SpliceAI_pred_DS_AL", "SpliceAI_pred_DS_DG", "SpliceAI_pred_DS_DL", "SpliceAI_score",
                'MOTIF_NAME', 'MOTIF_POS', "MOTIF_SCORE_CHANGE", "TRANSCRIPTION_FACTORS", 'FunMotifs', "Nearest_gene",
                "KRG", "K1", "gnomAD", "dbSNP"]
noncoding_colnames = ["ChIP", "DNase", "PWM", "Footprint", "QTL", "PWM_matched", "Footprint_matched", "ranking_probability", "Non_Coding_Score", "Non_Coding_Groups", "Coding_Score", "Coding_Group", "EA_enhancer", "GH_promoter", "GH_enhancer", "RefSeq_promoter", "GH_promoter_enhancer", "ENSEMBL_promoter", "mTL_miRNA",
                      "greendb_id", "greendb_stdtype", "greendb_dbsource", "greendb_genes", "green_constraint", "greendb_level", "ANN"]

len(noncoding_colnames)

26