In [1]:
from SigProfilerAssignment import Analyzer as Analyze
import sigProfilerPlotting as sigPlt
import os
import numpy as np
import pandas as pd
import shutil
import matplotlib.pyplot as plt 
import seaborn as sns

# SigProfilerAssignment (vcf input)
#1. conda deactivate
/opt/Yonsei/python/3.8.1/lib/python3.8/site-packages/SigProfilerAssignment/decomposition.py
'Unknown_signatures' :{'SBS':['8','12','16', '17a','17b','19','23','28','33','34','37','39','40','41', '89','91','93','94'], 'DBS':[], 'ID':[]} 
'Moore_signatures' : {'SBS':['3','6','8', '9','10','11', '12', '14', '15', '17', '19','20','21', '22','23', '24', '25', '26', '27', '28', '29', '30', '31', '33','34','36','37', '38', '39','40','41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '84', '85', '86', '87', '88',  '89', '90',  '92', '93','94'], 'DBS':[], 'ID':[]}

#2. conda activate cnvpytor  (remove가 붙음)
/home/goldpm1/miniconda3/envs/cnvpytor/lib/python3.7/site-packages/SigProfilerAssignment/decomposition.py

In [4]:
print( Analyze.__version__)

AttributeError: module 'SigProfilerAssignment.Analyzer' has no attribute '__version__'

In [3]:
input_data = '/data/project/Meningioma/41.Signature/01.SigProfiler/01.vcf/Tumor'
output_dir_assignment = '/data/project/Meningioma/41.Signature/01.SigProfiler/02.result_cosmic/Tumor/'
output_dir_extractor = '/data/project/Meningioma/41.Signature/01.SigProfiler/02.result_extract/Tumor'

if not os.path.exists(output_dir_assignment):
        os.makedirs(output_dir_assignment)

Analyze.cosmic_fit(input_data, output_dir_assignment, input_type = "vcf", genome_build="GRCh38", context_type = "96", exome =True,
                   signatures = None, signature_database = None, collapse_to_SBS96=False, make_plots = True,
                   exclude_signature_subgroups = ["remove_Chemotherapy_signatures", "remove_Treatment_signatures", "remove_Unknown_meningioma_signatures'"]
                    )  # "Artifact_signatures", exclude_signature_subgroups = ["Chemotherapy_signatures", "Treatment_signatures", "Test2"]

The specified genome GRCh38 has not been installed
Please refer to the SigProfilerMatrixGenerator README for installation instructions:
	https://github.com/AlexandrovLab/SigProfilerMatrixGenerator

SystemExit:

## SBS signature fitting stack bar

In [35]:
f = open(output_dir_assignment  + '/Assignment_Solution/Activities/Assignment_Solution_Activities.txt','r')

data = f.readlines()

column_name = data[0].rstrip().split('\t')
data_split = [x.rstrip().split('\t') for x in data[1:]]

df = pd.DataFrame(data_split, columns = column_name)
df = df.set_index(keys = 'Samples')

for i in df.columns:
    df[i] = pd.to_numeric(df[i])

# 0으로 가득찬 df는 filter하기
for column in df.columns:
    check = set()
    for value in df[column]:
        check.add(value)
    if len(check) == 1:
        df = df.drop(column, axis = 'columns')

df

,SBS1,SBS5,SBS6,SBS10a,SBS15,SBS16,SBS21,SBS23,SBS24,SBS28,...,SBS42,SBS45,SBS49,SBS52,SBS54,SBS58,SBS88,SBS93,SBS97,SBS98
Samples,,,,,,,,,,,,,,,,,,,,,
220930_2_Tumor,2,11,0,0,0,0,0,0,0,0,...,9,0,0,0,7,0,0,0,4,0
220930_Tumor,2,11,0,0,0,10,0,7,0,0,...,0,0,0,0,6,0,0,0,0,0
221026_Tumor,0,8,0,0,13,0,0,0,0,0,...,20,0,0,0,0,0,0,0,0,0
221102_Tumor,1,7,0,0,12,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
221202_Tumor,2,3,0,0,0,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
230127_Tumor,8,5,0,0,0,0,0,0,0,0,...,16,0,0,0,0,0,0,0,0,0
230303_Tumor,0,3,0,2,0,0,0,0,0,0,...,7,0,0,0,0,6,0,0,0,0
230323_2_Tumor,1,0,4,0,0,0,0,0,0,0,...,7,0,0,0,0,0,0,0,0,0
230405_2_Tumor,2,4,0,0,0,0,0,0,0,4,...,0,0,0,0,0,0,0,0,0,0
230419_Tumor,7,5,0,0,0,0,0,0,0,0,...,17,0,0,0,0,0,13,0,0,0
230526_Tumor,1,8,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3,3
230802_2_Tumor,0,0,0,0,0,0,0,0,0,0,...,0,7,9,0,0,0,0,0,0,0
230802_3_Tumor,4,0,0,0,45,0,0,0,0,0,...,187,0,0,0,0,0,0,0,0,0
230822_Tumor,0,3,0,0,4,0,0,0,0,0,...,12,0,0,0,0,0,0,0,0,0
230920_Tumor,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,15,0,0
231006_Tumor,7,0,0,0,0,0,0,0,9,0,...,0,0,0,0,0,0,0,0,0,0
240403_2_Tumor,0,20,0,0,0,0,0,0,0,0,...,0,0,153,0,0,0,0,0,0,0
240403_3_Tumor,10,0,0,0,0,0,0,0,0,0,...,95,0,0,0,0,0,0,0,0,0
240412_2_Tumor,0,5,0,0,4,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
240412_3_Tumor,0,0,0,0,38,0,0,0,0,0,...,105,0,0,25,0,0,0,0,0,0

### Percentage 로 변환하기

In [36]:
SBS_name = df.columns
total_count = {}

for index, row in df.iterrows():  ## index == A.~~ row = value
    total = 0
    for value in row:
        total += value
    total_count[index] = total

for index, row in df.iterrows():
    for idx, value in enumerate(row):
        df[SBS_name[idx]][index] = value/total_count[index]*100
        
df.astype(int)

,SBS1,SBS5,SBS6,SBS10a,SBS15,SBS16,SBS21,SBS23,SBS24,SBS28,...,SBS42,SBS45,SBS49,SBS52,SBS54,SBS58,SBS88,SBS93,SBS97,SBS98
Samples,,,,,,,,,,,,,,,,,,,,,
220930_2_Tumor,6,33,0,0,0,0,0,0,0,0,...,27,0,0,0,21,0,0,0,12,0
220930_Tumor,5,30,0,0,0,27,0,19,0,0,...,0,0,0,0,16,0,0,0,0,0
221026_Tumor,0,19,0,0,31,0,0,0,0,0,...,48,0,0,0,0,0,0,0,0,0
221102_Tumor,5,35,0,0,60,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
221202_Tumor,12,18,0,0,0,0,18,0,0,0,...,0,0,0,0,0,0,0,0,0,0
230127_Tumor,27,17,0,0,0,0,0,0,0,0,...,55,0,0,0,0,0,0,0,0,0
230303_Tumor,0,14,0,9,0,0,0,0,0,0,...,33,0,0,0,0,28,0,0,0,0
230323_2_Tumor,8,0,33,0,0,0,0,0,0,0,...,58,0,0,0,0,0,0,0,0,0
230405_2_Tumor,13,26,0,0,0,0,0,0,0,26,...,0,0,0,0,0,0,0,0,0,0
230419_Tumor,16,11,0,0,0,0,0,0,0,0,...,40,0,0,0,0,0,30,0,0,0
230526_Tumor,6,53,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,20,20
230802_2_Tumor,0,0,0,0,0,0,0,0,0,0,...,0,43,56,0,0,0,0,0,0,0
230802_3_Tumor,1,0,0,0,19,0,0,0,0,0,...,79,0,0,0,0,0,0,0,0,0
230822_Tumor,0,15,0,0,21,0,0,0,0,0,...,63,0,0,0,0,0,0,0,0,0
230920_Tumor,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,68,0,0
231006_Tumor,31,0,0,0,0,0,0,0,40,0,...,0,0,0,0,0,0,0,0,0,0
240403_2_Tumor,0,11,0,0,0,0,0,0,0,0,...,0,0,88,0,0,0,0,0,0,0
240403_3_Tumor,9,0,0,0,0,0,0,0,0,0,...,90,0,0,0,0,0,0,0,0,0
240412_2_Tumor,0,55,0,0,44,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
240412_3_Tumor,0,0,0,0,22,0,0,0,0,0,...,62,0,0,14,0,0,0,0,0,0

In [40]:
df.astype(int).iloc[:, -12:]

,SBS38,SBS39,SBS42,SBS45,SBS49,SBS52,SBS54,SBS58,SBS88,SBS93,SBS97,SBS98
Samples,,,,,,,,,,,,
220930_2_Tumor,0,0,27,0,0,0,21,0,0,0,12,0
220930_Tumor,0,0,0,0,0,0,16,0,0,0,0,0
221026_Tumor,0,0,48,0,0,0,0,0,0,0,0,0
221102_Tumor,0,0,0,0,0,0,0,0,0,0,0,0
221202_Tumor,0,50,0,0,0,0,0,0,0,0,0,0
230127_Tumor,0,0,55,0,0,0,0,0,0,0,0,0
230303_Tumor,0,0,33,0,0,0,0,28,0,0,0,0
230323_2_Tumor,0,0,58,0,0,0,0,0,0,0,0,0
230405_2_Tumor,0,0,0,0,0,0,0,0,0,0,0,0
230419_Tumor,0,0,40,0,0,0,0,0,30,0,0,0
230526_Tumor,0,0,0,0,0,0,0,0,0,0,20,20
230802_2_Tumor,0,0,0,43,56,0,0,0,0,0,0,0
230802_3_Tumor,0,0,79,0,0,0,0,0,0,0,0,0
230822_Tumor,0,0,63,0,0,0,0,0,0,0,0,0
230920_Tumor,0,0,0,0,0,0,0,0,0,68,0,0
231006_Tumor,27,0,0,0,0,0,0,0,0,0,0,0
240403_2_Tumor,0,0,0,0,88,0,0,0,0,0,0,0
240403_3_Tumor,0,0,90,0,0,0,0,0,0,0,0,0
240412_2_Tumor,0,0,0,0,0,0,0,0,0,0,0,0
240412_3_Tumor,0,0,62,0,0,14,0,0,0,0,0,0

In [38]:
fig, ax = plt.subplots( figsize=(12, 6), nrows = 1, ncols = 1 )
fig.subplots_adjust ( bottom = 0.25, top = 0.9, left = 0.05, right = 0.95)
sns.set_style("white")
ax.set_title ("Stacked bar chart", fontsize = 24, fontweight='heavy')
df.plot (kind = "bar", stacked=True , ax = ax)
ax.set_xticklabels (list ( df.index ), rotation  = 90, fontsize = 12, fontweight='bold')
ax.set_xlabel("")
plt.savefig ( output_dir_assignment  + "/Assignment_Solution/Activities/barchart.jpg", dpi = 300)
plt.show()

---

# DE NOVO SIGNATURE (SigProfilerExtractor)

In [9]:
from SigProfilerExtractor import sigpro as sig

input_data = '/data/project/Meningioma/41.Signature/01.SigProfiler/Dura/01.vcf'
output_dir_extractor = '/data/project/Meningioma/41.Signature/01.SigProfiler/Dura/03.extractor'

sig.sigProfilerExtractor (input_type = "vcf", output = output_dir_extractor, input_data = input_data, reference_genome="GRCh38", context_type = "96,DINUC,ID", exome =True,
                                    minimum_signatures=2, maximum_signatures=5, nmf_replicates=100, resample = True, batch_size=1, cpu=-1, gpu=False, 
                                    nmf_init="random", precision= "single", matrix_normalization= "gmm", seeds = "random", 
                                    min_nmf_iterations= 10000, max_nmf_iterations=1000000, nmf_test_conv= 10000, nmf_tolerance= 1e-15, get_all_signature_matrices= False,
                                    make_decomposition_plots = True)
                   #signatures = None, signature_database = None, collapse_to_SBS96=False, make_plots = True )

************** Reported Current Memory Use: 2.43 GB *****************

Starting matrix generation for SNVs and DINUCs...Completed! Elapsed time: 2.96 seconds.
Starting matrix generation for INDELs...Completed! Elapsed time: 2.22 seconds.
Matrices generated for 9 samples with 54 errors. Total of 1833 SNVs, 4 DINUCs, and 19 INDELs were successfully analyzed.
Extracting signature 2 for mutation type 96
The matrix normalizing cutoff is 9600


Time taken to collect 100 iterations for 2 signatures is 22.29 seconds
Optimization time is 3.966200590133667 seconds
The reconstruction error is 0.028, average process stability is 0.98 and
the minimum process stability is 0.95 for 2 signatures


Extracting signature 3 for mutation type 96
The matrix normalizing cutoff is 9600


Time taken to collect 100 iterations for 3 signatures is 34.24 seconds
Optimization time is 4.119777202606201 seconds
The reconstruction error is 0.195, average process stability is 0.47 and
the minimum process stability is -0.33 for 3 signatures


Extracting signature 4 for mutation type 96
The matrix normalizing cutoff is 9600


Time taken to collect 100 iterations for 4 signatures is 58.46 seconds
Optimization time is 4.0219268798828125 seconds
The reconstruction error is 0.1714, average process stability is 0.39 and
the minimum process stability is -0.34 for 4 signatures


Extracting signature 5 for mutation type 96
The matrix normalizing cutoff is 9600


Time taken to collect 100 iterations for 5 signatures is 111.54 seconds
Optimization time is 4.032492399215698 seconds
The reconstruction error is 0.0951, average process stability is 0.27 and
the minimum process stability is -0.63 for 5 signatures



 De Novo Fitting .....
|████████████████████████████████████████| 9/9 [100%] in 0.2s (52.24/s)

 Decomposing De Novo Signatures  .....
Decompositon Plot:SBS96A |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 1/1 [100%] in 0.0s (15698.83/s)
Decompositon Plot:SBS96B |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 1/1 [100%] in 0.0s (13851.95/s)

 Assigning decomposed signature
|████████████████████████████████████████| 9/9 [100%] in 0.3s (35.01/s)
Extracting signature 2 for mutation type DINUC
The matrix normalizing cutoff is 7800


Time taken to collect 100 iterations for 2 signatures is 15.15 seconds
Optimization time is 3.947788715362549 seconds
The reconstruction error is 0.0412, average process stability is 0.91 and
the minimum process stability is 0.81 for 2 signatures



 De Novo Fitting .....
|████████████████████████████████████████| 2/2 [100%] in 0.1s (39.44/s)

 Decomposing De Novo Signatures  .....
Decompositon Plot:DBS78A |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 1/1 [100%] in 0.0s (14595.13/s)
Decompositon Plot:DBS78B |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 1/1 [100%] in 0.0s (17175.05/s)

 Assigning decomposed signature
|████████████████████████████████████████| 2/2 [100%] in 0.1s (38.53/s)
Extracting signature 2 for mutation type INDEL
The matrix normalizing cutoff is 8300


Time taken to collect 100 iterations for 2 signatures is 22.56 seconds
Optimization time is 4.06881046295166 seconds
The reconstruction error is 0.6368, average process stability is 0.48 and
the minimum process stability is 0.43 for 2 signatures


There is no signature over the thresh-hold stability. We are selecting the lowest possible number of signatures.

 De Novo Fitting .....
|████████████████████████████████████████| 6/6 [100%] in 0.2s (37.69/s)

 Decomposing De Novo Signatures  .....
Decompositon Plot:ID83A |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 1/1 [100%] in 0.0s (15753.74/s)
Decompositon Plot:ID83B |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 1/1 [100%] in 0.0s (16609.64/s)

 Assigning decomposed signature
|████████████████████████████████████████| 6/6 [100%] in 0.2s (38.63/s)



Your Job Is Successfully Completed! Thank You For Using SigProfilerExtractor.

### cosine similarity

In [16]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

COSMIC_PATH = "/home/goldpm1/resources/COSMIC_SBS/COSMIC_v3.3.1_SBS_GRCh38.txt"
SIGPROFILER_DENOVO_DIR="/data/project/Meningioma/41.Signature/01.SigProfiler/Dura/03.extractor/SBS96/All_Solutions/SBS96_3_Signatures"
SIGPROFILER_DENOVO_TABLE_PATH = SIGPROFILER_DENOVO_DIR + "/Signatures/SBS96_S3_Signatures.txt"

COSMIC_df = pd.read_csv (COSMIC_PATH, sep = "\t")
SIGPROFILER_DENOVO_TABLE_df = pd.read_csv (SIGPROFILER_DENOVO_TABLE_PATH, sep = "\t")

In [39]:
# Compute cosine similarity
cos_sim = cosine_similarity( COSMIC_df.iloc[:, 1:COSMIC_df.shape[1]].values.transpose(), SIGPROFILER_DENOVO_TABLE_df.iloc[:,1:SIGPROFILER_DENOVO_TABLE_df.shape[1]].values.transpose()  )


# 가장 비슷한 (= cosine similarity가 가장 높은 SBS) SBS 찾기
for signature_i in range ( cos_sim.shape[1] ):
    lst = sorted(  cos_sim[:, signature_i], reverse=True)
    lst_arg = []
    for i in lst:
        lst_arg.append ( list(cos_sim[:, signature_i]).index (i) )

    max = np.max ( cos_sim[:, signature_i] )
    max_arg = np.argmax ( cos_sim[:, signature_i] )
    #print ("S{}\tmax = {}\tmax_arg = {}".format(signature_i + 1, round (max, 2), COSMIC_df.columns[ max_arg ] )) 
    print ("SBS96{}\tlst[0:5] = {}\t\tlst_arg[0:5] = {}".format ( chr(signature_i + 65), np.round (lst[0:5], 2) ,  COSMIC_df.columns [ [i for i in  lst_arg [0:5]] ]  )  )

SBS96A	lst[0:5] = [0.91 0.76 0.67 0.59 0.56]		lst_arg[0:5] = Index(['SBS48', 'SBS44', 'SBS37', 'SBS3', 'SBS52'], dtype='object')
SBS96B	lst[0:5] = [0.77 0.63 0.62 0.6  0.57]		lst_arg[0:5] = Index(['SBS93', 'SBS41', 'SBS44', 'SBS3', 'SBS37'], dtype='object')
SBS96C	lst[0:5] = [0.8  0.72 0.63 0.54 0.47]		lst_arg[0:5] = Index(['SBS14', 'SBS5', 'SBS41', 'SBS43', 'SBS22'], dtype='object')

In [40]:
COSMIC_df.iloc[:, 1:COSMIC_df.shape[1]].values.transpose().shape

(79, 96)